# Generated by Django 4.2.4 on 2023-08-04 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDetails',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('case_type', models.CharField(max_length=500)),
                ('case_filing_date', models.DateField()),
                ('complainant_name', models.CharField(max_length=500)),
                ('respondent_name', models.CharField(max_length=500)),
                ('registration_rera_number', models.CharField(max_length=100)),
                ('rera_project', models.CharField(max_length=500)),
                ('status_fixed_for', models.CharField(max_length=500)),
                ('bench_name', models.CharField(max_length=500)),
                ('court_address', models.TextField()),
                ('pending_for_date_of_decision', models.DateField()),
                ('additional_complainant_name', models.CharField(max_length=300)),
                ('additional_complainant_address', models.TextField()),
            ],
            options={
                'verbose_name': 'Case_Detail',
                'verbose_name_plural': 'Case_Details',
                'db_table': 'Case_details',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseTransferDetails',
            fields=[
                ('case_transfer_id', models.AutoField(primary_key=True, serialize=False)),
                ('case_from_bench', models.CharField(max_length=500)),
                ('case_to_bench', models.CharField(max_length=500)),
                ('transfer_number', models.CharField(max_length=300)),
                ('transfer_date', models.DateField()),
                ('transfer_remarks', models.TextField()),
            ],
            options={
                'verbose_name': 'Case_Transfer_Detail',
                'verbose_name_plural': 'Case_Transfer_Details',
                'db_table': 'Case_Transfer_details',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('order_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_doc_title', models.CharField(max_length=500)),
                ('order_date', models.DateField()),
                ('order_doc', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Order_Detail',
                'verbose_name_plural': 'Order_Details',
                'db_table': 'Order_details',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HearingRecordDetails',
            fields=[
                ('hearing_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('website_id', models.IntegerField()),
                ('bench_name', models.CharField(max_length=200)),
                ('next_hearing_date_fxed', models.DateField()),
                ('purpose_of_hearing', models.TextField()),
                ('date_fixed_for_proceeding', models.DateField()),
                ('case_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courtcases.casedetails')),
            ],
            options={
                'verbose_name': 'Hearing_record_Detail',
                'verbose_name_plural': 'Hearing_record_Details',
                'db_table': 'Hearing_record_detasils',
                'abstract': False,
            },
        ),
    ]
