# Generated by Django 4.2.4 on 2023-08-04 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courtcases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casedetails',
            old_name='additional_complainant_address',
            new_name='additional_complainant_details',
        ),
        migrations.RemoveField(
            model_name='casedetails',
            name='additional_complainant_name',
        ),
    ]
